macro-layout
js-tasks-ru/htmlcss-20221107_nepogodda pull request #10
Opened 2022-11-22 21:16 UTC by ola-9

2022-11-22 21:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-23 22:47 UTC, GSemikozov requested changes

2022-11-23 22:47 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_inner {
высоту все равно фиксировать не нужно, достаточно проставить нужные паддинги сверху и снизу

2022-11-23 22:47 UTC, GSemikozov commented on components/header/header.css
> +  height: 82px;
и тут не надо фиксировать

2022-11-23 22:47 UTC, GSemikozov commented on components/inner-page/inner-page.css
> +  width: 825px;
фиксировать ширину и высоту не надо, у ширины будет 1fr

2022-11-23 22:47 UTC, GSemikozov commented on components/menu/menu.css
> +.menu > nav > ul {
вложенные селекторы и селекторы тегов в БЭМ не используем, для ui нужно задать класс

2022-11-23 22:47 UTC, GSemikozov commented on components/menu/menu.css
> +.menu > nav > ul > li {
и тут

2022-11-25 20:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-25 21:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-25 21:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-25 21:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-26 09:46 UTC, ola-9 commented on components/header/header.css
> +  height: 82px;
а как тут тогда сделать? Если убрать высоту, то так как в блоке ничего нет, то его не видно, высота равна нулю.

2022-11-26 09:52 UTC, ola-9 commented on components/header/header.css
> +  height: 82px;
попробовала через `display: grid` сделать 0.4fr для этого элемента. Но так как все относительно, то как на макете высота в 82px не получается достигнуть. Может как-то еще можно сделать?

2022-11-26 09:58 UTC, ola-9 commented on components/inner-page/inner-page.css
> +  width: 825px;
убарала, но пришлось сделать модификатор у контейнера `container__inner-page `и задать ему `width: 100%` А может быть наоборот надо сделать `inner-page__container`??

2022-11-26 10:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-27 08:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-27 23:32 UTC, GSemikozov commented on components/header/header.css
> +  height: 82px;
да. -высота блока зависит от внутреннего контента + паддинги, поэтому 1. нужно учитывать высоту контента (лого - самый высоки элемент) 2. + паддинги сверху и снизу одинаковые
<img width="121" alt="Screenshot 2022-11-28 at 01 31 50" src="https://user-images.githubusercontent.com/6191270/204165573-ba6cb76a-5c9b-4799-89ce-39662e3c6a8c.png">

2022-11-27 23:38 UTC, GSemikozov requested changes

2022-11-27 23:38 UTC, GSemikozov commented on components/inner-page/inner-page.css
> +  grid-template-rows: 0.4fr 3fr auto;
auto 1fr auto

2022-11-27 23:38 UTC, GSemikozov commented on components/inner-page/inner-page.css
> +  width: 825px;
можно и через модификатор, но - модификатор пишется через 1 нижнее подчеркивание (`container_inner-page`) + такой модификатором не очень-то ясно говорит о том, что ИМЕННО он модифицирует. width: 100% можно задать сразу на .container (вместе с max-width)

2022-11-29 15:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-29 18:15 UTC, GSemikozov approved these changes

2022-11-29 18:15 UTC, merged