add content-image
js-tasks-ru/htmlcss-20221107_nepogodda pull request #12
Opened 2022-12-03 10:12 UTC by ola-9

2022-12-03 10:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-03 12:27 UTC, GSemikozov requested changes

2022-12-03 12:27 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +          <source srcset="./public/forest_768.jpg" media="(min-width: 768px)" />
если делаем через picture, тогда надо указать 2x здесь `srcset="./public/forest_400.jpg 1x, ./public/forest_768.jpg 2x"`

2022-12-03 12:33 UTC, ola-9 commented on 06-lection4/03-srcset/index.html
> +          <source srcset="./public/forest_768.jpg" media="(min-width: 768px)" />
а как это еще можно, если не через picture?

2022-12-03 13:07 UTC, ola-9 commented on 06-lection4/03-srcset/index.html
> +          <source srcset="./public/forest_768.jpg" media="(min-width: 768px)" />
тогда, наверное, `media `здесь нужно теперь убрать?

2022-12-03 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-05 14:55 UTC, GSemikozov approved these changes

2022-12-05 14:55 UTC, merged