add mobile layout of main and inner pages
js-tasks-ru/htmlcss-20221107_nepogodda pull request #14
Opened 2022-12-03 17:23 UTC by ola-9

2022-12-03 17:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-05 14:58 UTC, GSemikozov requested changes

2022-12-05 14:58 UTC, GSemikozov commented on components/component-preview/component-preview.css
> +    font-family: 'Inter', sans-serif;
все свойства дублировать не надо, только то, что меняется

2022-12-05 21:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 06:48 UTC, GSemikozov approved these changes

2022-12-06 06:48 UTC, merged