add tabs on main page:
js-tasks-ru/htmlcss-20221107_nepogodda pull request #19
Opened 2022-12-11 12:34 UTC by ola-9

- refactor desktop and mobile layout
- fill tabs with components

2022-12-11 12:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-14 23:23 UTC, GSemikozov requested changes

2022-12-14 23:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-text {
что это за другой блок внутри блока .button?)
или это модификатор .button_text?

2022-12-14 23:23 UTC, GSemikozov commented on 07-lection5/03-toggler/index.html
> +  <div class="toggler">
в случае с инпутами как раз все оставляем завернутым в label - у нас же таким образом привязка к изменению состояния инпута + не надо задавать id

2022-12-14 23:23 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__scroller-item_active {
чуть выше уже есть такой класс

2022-12-17 09:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-23 14:07 UTC, GSemikozov approved these changes

2022-12-23 14:07 UTC, GSemikozov commented on components/card/card.css
> +    width: 80%;
лишнее, у нас контейнер добавит отступов по краям тобы карточка не прилипала к краям

2022-12-23 14:07 UTC, merged