complete lection-2 homework
js-tasks-ru/htmlcss-20221107_nepogodda pull request #6
Opened 2022-11-19 13:24 UTC by ola-9

2022-11-19 13:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-19 15:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-20 14:02 UTC, GSemikozov requested changes

2022-11-20 14:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  /* Почему вложенные блоки не наследуют параметры шрифта? */
обсуждали на лекции - проблема в шрифте который задаем в main.css через `*`

2022-11-20 14:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex: 1 0 auto;
это в принципе лишнее, мы ширину прописываем явно

2022-11-20 14:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line:last-child {
лучше использовать gap на уровне родителя, иначе никогда не знаешь какой элемент будет последним )

2022-11-20 14:02 UTC, GSemikozov commented on components/card/card.css
> +  font-size: 16px;
точно надо?)

2022-11-22 20:22 UTC, ola-9 commented on 04-lection2/02-skeleton/skeleton.css
> +  flex: 1 0 auto;
не совсем понимаю, вместо  flex проставить `width: 100%`?

2022-11-22 20:29 UTC, ola-9 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line:last-child {
Можно сделать, но тогда мне придется добавить для них обертку которая будет `display:flex`. Сейчас они просто в обычном потоке идут с `margin-bottom`.  Может еще какой-то вариант есть?

2022-11-22 20:34 UTC, ola-9 commented on 04-lection2/01-histogram/histogram.css
> +  /* Почему вложенные блоки не наследуют параметры шрифта? */
да, это я поправила, у меня там именно с размеров шрифта не получается.  вот [codepen](https://codepen.io/Oceanpacific/pen/WNyMWXM?editors=1100) где можно это увидеть.

2022-11-22 20:35 UTC, ola-9 commented on components/card/card.css
> +  font-size: 16px;
точно, это не нужно тут.

2022-11-23 22:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  /* Почему вложенные блоки не наследуют параметры шрифта? */
ответил в личку

2022-11-23 22:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex: 1 0 auto;
если ширина прописывается явно (в модификаторах прописана, а по умолчанию блочный элемент растягивается на 100% ширины), тогда эта строка лишняя

2022-11-23 22:40 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line:last-child {
обертку не надо, у каждого набора линий есть свой родитель, вот этому родителю и можно задать `display: flex; flex-direction: column; gap: 8px;`

2022-11-26 13:14 UTC, GSemikozov requested changes

2022-11-26 13:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  color: var(--black);
вот здесь не хватает общих паддингов

2022-11-26 13:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  color: var(--black);
это именно внутренняя реализация блока, а не часть например component-wrapper (+ component-wrapper должен быть не на одном уровне с .histogram, .histogram - "завернут" в component-wrapper

2022-11-26 13:14 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  gap: 8px;
не хватает паддингов

2022-11-26 13:14 UTC, GSemikozov commented on components/component-wrapper/component-wrapper.css
> +.component-wrapper_skeleton {
такие модификаторы не надо добавлять, паддинги внутри блока - это его внутренняя реализация

2022-11-27 23:38 UTC, GSemikozov approved these changes

2022-11-27 23:39 UTC, merged