add calendar component
js-tasks-ru/htmlcss-20221107_nepogodda pull request #9
Opened 2022-11-22 20:55 UTC by ola-9

2022-11-22 20:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-23 22:44 UTC, GSemikozov requested changes

2022-11-23 22:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
`28 26 32`

2022-11-26 13:14 UTC, GSemikozov approved these changes

2022-11-26 13:15 UTC, merged